#include "VWAPEngine.h"
#include <iostream>
#include <chrono>

int main() {
    const std::string datafile = "market_data.csv";
    VWAPEngine engine;

    std::cout << "Starting high-throughput VWAP aggregation...\n";

    // Standard C++ Benchmarking using the high-resolution clock
    auto start = std::chrono::high_resolution_clock::now();

    if (!engine.processCSV(datafile)) {
        std::cerr << "Execution failed. Did you run the data_generator first?\n";
        return 1;
    }

    auto end = std::chrono::high_resolution_clock::now();
    std::chrono::duration<double> diff = end - start;

    engine.printResults();

    std::cout << "\n====================================\n";
    std::cout << "   PERFORMANCE BENCHMARK            \n";
    std::cout << "====================================\n";
    std::cout << "Time Elapsed : " << diff.count() << " seconds\n";
    
    // Calculate throughput. Assuming 5 million rows generated by the script.
    std::cout << "Throughput   : " << (5'000'000 / diff.count()) / 1'000'000.0 << " Million rows/sec\n";
    std::cout << "====================================\n";

    return 0;
}